name: Android Develop CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build_qa_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache stuff
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew lint jacocoUnitTestReport

      #    - name: Upload lint results
      #      uses: actions/upload-artifact@v1.0.0
      #      with:
      #        name: test-results
      #        path: payroc-sdk/build/reports/

# TODO - create a signed build.
#
#      - name: Generate Debug AAR with Gradle
#        if: success()
#        run: ./gradlew assembleDebug
#
#
#      - name: Upload AAR artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: payroc_android_demo_app-debug_${{ github.head_ref }}
#          path: payroc_android_demo_app/build/outputs

# Upload to S3 bucket and link to slack.
#    - name: Post result to Slack
#      run: echo "TBD if build succeeds or fails."
